[package]
name = "qrcodes"
version = "0.0.1-alpha"
authors = ['veaba< Godpu@outlook.com>']
description = "QRcode for rust wasm."
repository = "https://github.com/veaba/qrcodes"
license = "MIT"
edition  = '2021'

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
wasm-bindgen = "0.2.88"
js-sys = "0.3.60"
web-sys = { version = "0.3.60", features = ["console"] }
console_error_panic_hook = { version= "0.1.6", optional = true}
wee_alloc = { version = "0.4.5",optional = true}
rayon = { version = "1.7", optional = true }
wasm-bindgen-rayon = { version = "1.3", optional = true }

[features]
default = ['console_error_panic_hook']
parallel = ['wasm-bindgen-rayon', 'rayon']

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
